### ISSUE TITLE
Tessera does not working correctly when using start-all.sh on EC2

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-graphite-monitoring#1]
The web server is available on 8081, but it can not reach the graphite to get the data.
The problem is with the GRAPHITE_URL in the following:

```
sudo docker run -d \
    -p 8081:80 \
    -e GRAPHITE_URL=http://127.0.0.1:80 \
    -it scylladb/scylla-monitoring:tessera
```

This URL is used from the **browser**, hence should be the instance external IP, not 127.0.0.1

**Comment by tgrabiec** [comment]
@tzach The address reachability issue is mentioned in the README, `start-all.sh` was mainly intended as a helper for starting locally. Perhaps we could modify it to accept the bind address as parameter.

**Comment by tzach** [comment]
@tgrabiec yes, more an observation than a bug.
For EC2, I'm adding an Ansible playbook which will take care of that.

**Comment by tzach** [comment]
Solve by introducing start-all-ec2.sh in 
in https://github.com/scylladb/scylla-monitoring/pull/4
